language: ruby
rvm:
  - 2.5.3
services:
  - postgresql
before_script:
  - psql -c 'create database my_contacts_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: ZforMwdLu86ZGaa6AUA66mt40eb6xbhqYLn9w+qT1JTrmoUo3UDjpIPLQyUllWA+/hqnAnmV8DyYRKR4OkNkod/pEzqeOOnY8z1OUqlQM/q5m7Q2JpmbLx7Z1Re1MX2yrVJ3yCNrwLX2RyabPg8JUGiCFABfDjLHZjh7Qf7jdLpfAG7xJlRTjJEQA1SimJ45HMklqGGFf25ykwfsp/bKIRMGbn2hrOgzsODhotJsFfAP296PCbIDfYx3GvqkP5jWpY08IFO45xvRQ6bvzs+AlF6Hyfb0FWiIbdbb0Mr+X7WeOuJtgRWwB5iFKq6ixXb855yjBo8XVVEPBQpRaHo6cM/4Yvfk3X9n3b9+WPGLXxG6FRFf/1nFsIoVQpCxlaUy28H/7c/qfRmwxCkxQ8aV7JrZx6ql9qdLBGQZA3WH/qP1FI4Ir7B/nMQkpuhXMhlER5dCzHIKYpNdKOpwzVVVHz9simWCFQ+fhHtyQTSM2ohb3Mr7thTxAE7TPptvXe1DEKYS0+OEaheHpzkqO3qpULu1KzKAZwKKk6KesTkg5o9CbswNq6weNUtDyJbPjdOyzuf56YU07DWq78LUtTU+28kI0xaLrOt7b9ui1HUCfBlPUyQ4pQxz0QR/64U9I+tHlU2LCjdBkx1VqHy0V/Jegoc2TXty7DQcjZ0pJjBX+fk=
  app: enigmatic-taiga-18280
  on:
    branch: master
