swagger: "2.0"
info:
  title: MyContacts Api
  description: This is a sample server.
  termsOfService: "http://open-api.io/terms/"
  contact:
    name: API Support
    url: "http://www.open-api.io/support"
    email: support@open-api.io
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: 1.0.0
host: <%= ENV.fetch('DEFAULT_HOST', 'localhost:3000') %>
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
