default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV.fetch('POSTGRES_PORT') { 5432 } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

production:
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

test:
  <<: *default
  database: my_contacts_test
